config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  resources :projects

  get "project/:project_id/comments/sorted" => "comments#sorted" , as: :project_comments_sorted
  
  resources :comments, controller: :comments do
  	resources :subcomments , controller: :comments 
  	resources :up_votes
  end

  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :project
	has_many :sub_comments, class_name: "Comment", foreign_key: :comment_id

	has_many :upvotes, class_name: "UpVote"

	def comment
		Comment.find(self.comment_id)
	end
end

app/models/commit.rb
class Commit < ApplicationRecord
	belongs_to :project_file
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :project_files
	has_many :comments
end

app/models/project_file.rb
class ProjectFile < ApplicationRecord
	belongs_to :project
	has_many :commits
end

app/models/up_vote.rb
class UpVote < ApplicationRecord
	belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
  	params[:comment][:statement] = params[:comment][:statement].gsub(/fuck/i, 'fudge')
  	params[:comment][:statement] = params[:comment][:statement].gsub(/hell/i, 'heck')
  	params[:comment][:statement] = params[:comment][:statement].gsub(/bitch/i, 'person')
  	params[:comment][:statement] = params[:comment][:statement].gsub(/dumbass/i, 'stupid')
  	params[:comment][:statement] = params[:comment][:statement].gsub(/asshole/i, 'jerk')
  	@comment = Comment.new(comments_params)

    if params[:comment_id]
      @comment.comment_id = params[:comment_id]
    end

    @comment.save

    if(@comment.errors)
      puts "================================================================================="
      puts @comment.errors.messages
      puts "================================================================================="
    end

    @comments = @comment.project.comments

    @html = ApplicationController.render(partial: "projects/comments", locals: { comments: @comments.where(comment_id: nil) }, formats: [:html])
     

    render json: { html: @html ,comment: @comment, comments: @comments ,upvotes_count: @comment.upvotes.count , status: "200"}
  end

  def sorted 
    if params[:by] == "upvotes"
      
      # @comments = Comment.joins(:upvotes).where(project_id: params[:project_id]).group("comments.id").order("count('up_votes.id') desc")
      
      @comments = Comment.where(project_id: params[:project_id],comment_id: nil)
      comment_votes_hash = @comments.map do |comment|
        {
          comment: comment,
          votes_count: comment.upvotes.count
        }
      end

      sorted_votes_comments = comment_votes_hash.sort_by { |k| k[:votes_count]}.reverse

      # @comments = Comment.where(project_id: 1,comment_id: nil)
      # comment_votes_hash = @comments.map do |comment|
      #   {
      #     comment: comment,
      #     votes_count: comment.upvotes.count
      #   }
      # end

      # sorted_votes_comments = comment_votes_hash.sort { |k| k[:votes_count]}

      puts "========================================================================="
      puts sorted_votes_comments
      puts "========================================================================="

      sorted_comments = sorted_votes_comments.map { |k| k[:comment] } 

      puts "========================================================================="
      puts sorted_comments
      puts "========================================================================="

      @html = commentsRenderer(sorted_comments)

      render json: { html: @html }

    elsif params[:by] == "subcomments" 
      
      @comments = Comment.where(project_id: params[:project_id],comment_id: nil)

      commentHash = @comments.map do |comment|
        count = 0
        count += comment.sub_comments.count
        comment.sub_comments.each do |subcomment|
            count += subcomment.sub_comments.count
            subcomment.sub_comments.each do |subsubcomment|
              count += subsubcomment.sub_comments.count
            end
        end
        {
          comment: comment,
          count: count
        }
      end

      puts "============================================================================="
      puts commentHash
      puts "============================================================================="

      sortedHash = commentHash.sort_by{ |k| k[:count] }.reverse

      puts "============================================================================="
      puts sortedHash
      puts "============================================================================="

      @commentsArray = sortedHash.map {|k| k[:comment]}

      # @comment = Comment.where(project_id: params[:project_id]).group(:comment_id).order("count(comment_id) asc") + Comment.where(project_id: params[:project_id],comment_id: nil)
      @html =  commentsRenderer(@commentsArray)

      render json: { html: @html } 
    end  
  end

  private

    def commentsRenderer comments
      ApplicationController.render(partial: "projects/comments", locals: { comments: comments }, formats: [:html])
    end

  	def comments_params
  		params.require(:comment).permit(:project_id, :statement)
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	@projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def show
  	@project = Project.find(params[:id])
  	@project_files = @project.project_files
  	@last_commit = Commit.where(project_file_id: @project_files.pluck(:id)).last
  	@comment = @project.comments.new
  	@comments = @project.comments.where(comment_id: nil).order("created_at DESC")
  end
end

app/controllers/up_votes_controller.rb
class UpVotesController < ApplicationController
	def create
		@upvote = UpVote.new(comment_id: params[:comment_id])
		if @upvote.save
			render json: {status: :ok}
		else 
			render json: {status: "400"}
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/up_votes_helper.rb
module UpVotesHelper
end

app/views/home/index.html.erb
<header>
  <div class="container" id="maincontent" tabindex="-1">
    <div class="row">
      <div class="col-lg-12">
        <%= image_tag 'profile.png', class: "img-responsive" %>
        <div class="intro-text">
            <h1 class="name">Jin Li's Web Portfolio</h1>
            <hr class="star-light">
            <span class="skills">Web Developer</span>
        </div>
      </div>
    </div>
  </div>
</header>
<section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Portfolio</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
        	<% @projects.zip(['cabin.png', 'cake.png', 'circus.png', 'game.png', 'safe.png' ]).each do |project, image_path| %>
	            <div class="col-sm-4 portfolio-item">
	                <a href="<%= project_path(project) %>" class="portfolio-link" data-toggle="modal">
	                    <div class="caption">
	                        <div class="caption-content">
	                            <i class=""><%= project.name %></i>
	                        </div>
	                    </div>
	                    <%= image_tag image_path, class: "img-responsive" %>
	                </a>
	            </div>
	        <% end %>
        </div>
    </div>
</section>
<section class="success" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>About</h2>
                <hr class="star-light">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-lg-offset-2">
                <p>I am currently a student at University of Urbana-Champaign</p>
            </div>
            <div class="col-lg-4">
                <p>This is where I showcase my work.</p>
            </div>
        </div>
    </div>
</section>

app/views/layouts/_top_nav.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom affix">
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">JIN LI WEBPORTFOLIO</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden active">
            <a href="#"></a>
        </li>
        <li class="page-scroll">
            <a href="#">Portfolio</a>
        </li>
        <li class="page-scroll">
            <a href="#">About</a>
        </li>
        <li class="page-scroll">
            <a href="#">Contact</a>
        </li>
      </ul>
    </div>
      <!-- /.navbar-collapse -->
  </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectParser</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top" class="index">
  	<%= render 'layouts/top_nav' %>
    <div >
      <%= yield %>    
    </div>
  </body>
</html>

app/views/projects/_comment.html.erb
<div>
	<p>
		<span style="font-size: small; color: gray"> 
			<%= time_ago_in_words comment.created_at %> ago 
			<span id="upvote-comment-id-<%= comment.id %>">
				upvotes : <span id="upvote-comment-id-<%= comment.id %>-count"><%= comment.upvotes.count %></span>
			</span> 
		</span> 
		<br>
		<%= comment.statement %>			
	</p>

	<!-- upvote button -->
	<button type="button" class="btn btn-primary" id="upvote_button"  onclick="upVote(<%= comment.id %>)">Up Vote</button>	
</div>

app/views/projects/_commentform.html.erb
<div id="comment-form">
	<hr>	
	<textarea id="comment" class="form-control" name=""></textarea>
	<button type="button" class="btn btn-success pull-right" onclick="createNewComment()">Comment</button>
	<hr>	
</div>

app/views/projects/_comments.html.erb
<div>

	<% comments.each do |comment| %>

		<%= render "projects/comment", comment: comment %>

		<div style="margin-left: 60px;">
			<% comment.sub_comments.each do |subcomment| %>
				<%= render "projects/comment", comment: subcomment %>	
				<div style="margin-left: 120px;">
					<% subcomment.sub_comments.each do |subsubcomment| %>
						<%= render "projects/comment" , comment: subsubcomment %>

						<div style="margin-left: 180px">
							<% subsubcomment.sub_comments.each do |subsubsubcomment| %>
								<%= render "projects/comment", comment: subsubsubcomment %>
							<% end %>
							<%= render "projects/subcommentform", comment: subsubcomment %>
						</div>
					<% end %>
					<%= render "projects/subcommentform", comment: subcomment %>	
				</div>
			<% end %>
			<%= render "projects/subcommentform", comment: comment %>
		</div>
	<% end %>

	<%= render "projects/commentform" %>

</div>

app/views/projects/_subcommentform.html.erb
<div id="comment-form">
	<hr>	
	<textarea id="sub-comment-<%= comment.id %>" class="form-control" name=""></textarea>
	<button type="button" class="btn btn-success pull-right" onclick="createSubComment(<%= comment.id %>)">Comment</button>
	<hr>	
</div>

app/views/projects/show.html.erb
<div class="container" style="margin-top: 60px; margin-left: 15px; ">
	<h2><%= @project.name %></h2>
	<table class="table ">
		<tr>
			<td>Version</td>
			<td><%= @last_commit.revision if @last_commit%></td>
		</tr>
		<tr>
			<td>Summary</td>
			<td><%= @last_commit.message if @last_commit %></td>
		</tr>
	</table>
	<br>
	<h3>Project Files</h3>
	<table class="table table-stripped">
		<thead>
			<th>Name</th>
			<th>Size</th>
			<th>Path</th>
			<th>Type</th>
		</thead>
		<tbody>
			<% @project_files.try(:each) do |file| %>
				<tr>
					<td> <%= file.name %> </td>
					<td> <%= file.size %> </td>
					<td> <%= file.path %> </td>
					<td> <%= file.file_type %> </td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<h3>Comments: </h3>

	<hr>
		<select class="form-control" id="sortby-select" onchange="getSorted()">
			<option value="upvotes">upvotes</option>
			<option value="subcomments">subcomments</option>
		<select>
	<hr>

	<img id="spinner" src="/4.gif" className="img img-responsive" style="margin:auto;position:fixed;z-index: 999;overflow:hidden;margin: auto;top: 0;left: 0;bottom: 0;right: 0"/>
	
	<div id="comments-div">
		<%= render "comments",comments: @comments %>	
	</div>

	<hr>
	
	<br><br><br>
</div>

<script>

	$(document).ready(function(){
		$("#spinner").hide();
	})

	var getSorted = function(){
		$("#spinner").show();
		$.ajax({
			url: Routes.project_comments_sorted_path('<%= @project.id %>')+"?by="+$("#sortby-select").val(),
			method: "get",
			success: function(data){
				console.log(data)
				$("#spinner").hide();
				$("#comments-div").html(data.html)
			},
			failure: function(){
				$("#spinner").hide();
				alert("error loading the sorted comments")
			}
		})
	}

	var createSubComment = function(comment_id){
		$("#spinner").show();
		console.log($("#sub-comment-"+comment_id).val());
		var comment = $("#sub-comment-"+comment_id).val();
		var project_id = '<%= @project.id %>';
		

		if(comment != ""){
			$.ajax({
				url: Routes.comment_subcomments_path(comment_id),
				method: "post",
				data: {
					comment: {
						statement: comment,
						project_id: project_id
					},
					
				},
				success: function(data){
					console.log(data);
					$("#comments-div").html(data.html);
					getSorted();
					$("#spinner").hide();
				},
				failure: function(){
					alert("message sending failed")
					$("#spinner").hide();
				}
			})
		}else{
			$("#spinner").hide();
			alert("cannot post empty comment")
		}
	}

	var createNewComment = function(e){
		$("#spinner").show();
		var comment = $("#comment").val();
		var project_id = '<%= @project.id %>';
		if(comment != ""){
			$.ajax({
				url: Routes.comments_path(),
				method: "post",
				data: {
					comment: {
						statement: comment,
						project_id: project_id
					},
					
				},
				success: function(data){
					$("#comments-div").html(data.html);	
					getSorted();
					$("#spinner").hide();				
				},
				failure: function(){
					alert("message sending failed")
					$("#spinner").hide();
				}
			})
		}else{
			alert("cannot post empty comment")
			$("#spinner").hide()
		}
	}


	var updateUpvotes = function(comment_id){
		var html = $("#upvote-comment-id-"+comment_id+"-count").html();
		 $("#upvote-comment-id-"+comment_id+"-count").html(parseInt(html)+1);
	}

	var upVote = function(comment_id){
		$("#spinner").show();
		$.ajax({
			url: Routes.comment_up_votes_path(comment_id),
			method: "post",
			success: function(){
				console.log("success");
				updateUpvotes(comment_id);
				getSorted();
				$("#spinner").hide();
			},
			failure: function(){
				console.log("failure");
				$("#spinner").hide();
			}
		})
		
	}

</script>